### ISSUE TITLE
eslint error: "Cannot find module .../dist/Checkbox"

### ISSUE THREAD

**Issue by ysmike** [react-native-checkbox/react-native-checkbox#111]
When I run `yarn run eslint .`, I'm running into the error below. In `package.json`, there is this line `"main":"dist/Checkbox"`; however, in the `dist` folder of the module, there is no file that matches `Checkbox`. If I manually change the `package.json` file to match one of the files in the `dist` folder, eslint does pass but this doesn't feel right. Any thoughts? https://github.com/react-native-checkbox/react-native-checkbox/issues/34#issuecomment-748033674 also addressed this issue.

`Error: Cannot find module '.../node_modules/@react-native-community/checkbox/dist/CheckBox'. Please verify that the package.json has a valid "main" entry`

**Comment by nicholaslee119** [comment]
@ysmike @vergho
0.5.8 was released to fix this bug
