### ISSUE TITLE
Checkobx not working on ios 

### ISSUE THREAD

**Issue by hanaechahid** [react-native-checkbox/react-native-checkbox#113]
Hi everyone,
I just installed that, it works well on android but I get an error on IOS.

`Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.`

here is My react native versions:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
    "@react-native-community/checkbox": "^0.5.7"
after I do pod install on ios folder, I get this: 
````
npx : 1 installé(s) en 2.332s
Scanning for pods...
1.9.1
> pod install
Analyzing dependencies
[!] Unable to find a specification for `React-Core` depended upon by `RNCCheckbox`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Aborting run
An unexpected error was encountered. Please report it as a bug:
{ CocoaPodsError: The command `pod install` failed
└─ Cause: Error: pod exited with non-zero code: 1
````

help please it's urgent. Thank you for you all!

**Comment by rakicluca** [comment]
I'm using it with expo sdk 40 and I have the same problem... Android works fine but in IOS I can't even start the app because of this... Can anyone help?

**Comment by fabervae** [comment]
They mention on the [front page](https://github.com/react-native-checkbox/react-native-checkbox#support) that V0.2 is the latest version which supports RN 0.59 and below (Android only).
I'm not a maintainer. If possible, try to upgrade to RN 0.60+. [This tool](https://react-native-community.github.io/upgrade-helper/?from=0.59.0&to=0.63.3) might help, though it definitely depends on how old your dependencies are.

**Comment by hanaechahid** [comment]
hello @rakicluca , for me I solved the problem for ios by creating a checkbox component using native elements. so on ios I called the created component and android this one and that's it. without upgrading react native version

**Comment by rakicluca** [comment]
hi @hanaechahid, thanks for reply! I see that with react native elements but I want to use this one... For the moment I will use the react native elements version... Anyway thank you for the advice ;)
