### ISSUE TITLE
Help needed: Add custom unchecked icon

### ISSUE THREAD

**Issue by alakdam07** [react-native-checkbox/react-native-checkbox#132]
Thank you for this nice package. I want to add custom unchecked icon. Currently if the value the false then unchecked UI is empty box, instead showing empty box I want to display like this: 
<img width="43" alt="Screenshot 2021-07-05 at 16 15 19" src="https://user-images.githubusercontent.com/47625626/124477081-4532c280-ddac-11eb-8a3c-7cb38e45f0fb.png">

Is the any possible to do that?

**Comment by codal-hkrishnani** [comment]
@alakdam07 what was the solution?

**Comment by wahidshadab** [comment]
@alakdam07 Can you share the solution please?

**Comment by alakdam07** [comment]
The question I published year ago. I don't even remember did I solve the issue? Sorry 😞
