### ISSUE TITLE
requireNativeComponent: "AndroidCheckBox" was not found in the UIManager.

### ISSUE THREAD

**Issue by chinmayk3** [react-native-checkbox/react-native-checkbox#151]
I am trying to install Checkbox in react native using **npm install @react-native-community/checkbox --save** but getting this error everytime : **requireNativeComponent: "AndroidCheckBox" was not found in the UIManager.**

**Comment by nazmiahmeti** [comment]
I'm facing the same issue. I would love to find out whats the problem here!

**Comment by shubham-bawa-mcsam** [comment]
I'm facing the same issue too

**Comment by chinmayk3** [comment]
Hi all , I have found a new way to use checkbox i.e  '**expo install expo-checkbox**' and then **import Checkbox from "expo-checkbox"**
`<Checkbox
          style={styles.checkbox}
          value={isChecked}
          onValueChange={setChecked}
          color={isChecked ? '#4630EB' : undefined}
        />`

**Comment by shubham0804** [comment]
@chinmayk3 Thanks for the solution. I'm not using expo. If anyone finds a solution for react native cli, pl comment.

**Comment by nazmiahmeti** [comment]
@chinmayk3 thanks a lot mate. I really appreciate it. I got another question. Is there anyway to customize checkbox icon!
I researched a bit and nothing found. If you have any information I would love to know. Thanks in advance.

**Comment by chinmayk3** [comment]
> @chinmayk3 Thanks for the solution. I'm not using expo. If anyone finds a solution for react native cli, pl comment.

Hi @shubham0804  , I have used this in react-native-cli project.  Not in expo project.

**Comment by chinmayk3** [comment]
> @chinmayk3 thanks a lot mate. I really appreciate it. I got another question. Is there anyway to customize checkbox icon! I researched a bit and nothing found. If you have any information I would love to know. Thanks in advance.

I will let you know.
