### ISSUE TITLE
when disabled and value both have initial value as true, checked icon is not shown on ios

### ISSUE THREAD

**Issue by SupriyaAdep** [react-native-checkbox/react-native-checkbox#157]
react-native-checkbox version: 0.5.10
react-native: 0.63.3
platform: ios 15

When checkbox component is disabled and initial value is true, the tick icon is not visible, this was working in 0.5.9, but it had "Could not resolve dependency error for react-native-windows".

Any suggestions or feedback will be helpful.

Thank you

**Comment by goguda** [comment]
> react-native-checkbox version: 0.5.10 react-native: 0.63.3 platform: ios 15
> 
> When checkbox component is disabled and initial value is true, the tick icon is not visible, this was working in 0.5.9, but it had "Could not resolve dependency error for react-native-windows".
> 
> Any suggestions or feedback will be helpful.
> 
> Thank you

Can confirm as well, works properly on iOS on v 0.5.9 but on 0.5.10 and 0.5.11 the value prop seems to have no effect when changed via means other than clicking the checkbox itself.

**Comment by billnbell** [comment]
same with us!

**Comment by billnbell** [comment]
This is a MAJOR issue.

**Comment by billnbell** [comment]
Here is a fix. When you added value, it removed it from sending to IOS module.

File: @react-native-community+checkbox+0.5.11.patch

```
diff --git a/node_modules/@react-native-community/checkbox/dist/CheckBox.ios.js b/node_modules/@react-native-community/checkbox/dist/CheckBox.ios.js
index 8149f11..163e372 100644
--- a/node_modules/@react-native-community/checkbox/dist/CheckBox.ios.js
+++ b/node_modules/@react-native-community/checkbox/dist/CheckBox.ios.js
@@ -84,7 +84,7 @@ var CheckBox = /** @class */ (function (_super) {
             }, accessibilityValue: { text: value || false ? 'on' : 'off' } },
             react_1.default.createElement(IOSCheckBoxNativeComponent_1.default, __assign({}, props, { 
                 // @ts-ignore TODO: implement the type of IOSCheckBoxNativeComponent
-                style: [styles.rctCheckBox, style], ref: this._setNativeRef, onValueChange: this._onChange }))));
+                style: [styles.rctCheckBox, style], ref: this._setNativeRef, value: value, onValueChange: this._onChange }))));
     };
     return CheckBox;
 }(react_1.default.Component));
```

**Comment by billnbell** [comment]
Also https://github.com/react-native-checkbox/react-native-checkbox/pull/159

**Comment by matthewjhough** [comment]
I'm also affected by this issue, is there any discussion/movement in getting [your PR reviewed](https://github.com/react-native-checkbox/react-native-checkbox/pull/159) and approved @billnbell ?

**Comment by nicholaslee119** [comment]
Thanks for your report, I am reviewing this issue

**Comment by nicholaslee119** [comment]
Hi, everyone!  The new version 0.5.12 was just released to fix this problem

**Comment by SupriyaAdep** [comment]
Thank u @nicholaslee119. will close this issue.
