### ISSUE TITLE
 ERROR  Invariant Violation: requireNativeComponent: "AndroidCheckBox" was not found in the UIManager.

### ISSUE THREAD

**Issue by kmkz-69** [react-native-checkbox/react-native-checkbox#176]
This error is located at:
    in AndroidCheckBox (created by CheckBox)
    in CheckBox
    in CheckBoxWithRef (created by CheckBox)
    in RCTView (created by View)
    in View (created by CheckBox)
    in RCTView (created by View)
    in View (created by Container)
    in Container (created by CheckBox)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by TouchableOpacity)
    in TouchableOpacity (created by TouchableOpacity)
    in TouchableOpacity (created by CheckBox)
    in CheckBox (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Online_Learning(RootComponent), js engine: hermes

 "dependencies": { 
              "@react-native-community/checkbox": "^0.5.12",
              "@react-navigation/bottom-tabs": "^6.3.3",
              "@react-navigation/drawer": "^6.4.4",
              "@react-navigation/native": "^6.0.12",
              "@react-navigation/native-stack": "^6.8.0",
              "lottie-react-native": "^5.1.4",
              "react": "18.1.0",
              "react-native": "0.70.0",
              "react-native-appearance": "^0.3.4",
              "react-native-gesture-handler": "^2.6.0",
              "react-native-modal": "^13.0.1",
              "react-native-reanimated": "^2.10.0",
              "react-native-safe-area-context": "^4.3.3",
              "react-native-screens": "^3.17.0",
              "react-native-snap-carousel": "^3.9.1",
              "react-native-svg": "^13.1.0",
              "react-native-vector-icons": "^9.2.0"
 }

import RNCheckBox from '@react-native-community/checkbox';

 <RNCheckBox
            value={checked}
            onCheckColor="transparent"
            onTintColor={primary}
            onFillColor={primary}
            tintColors={{
              true: primary,
              false: text,
            }}
            onAnimationType="bounce"
            offAnimationType="bounce"
          />

**Comment by Julioevm** [comment]
Same issue, using Expo if that matters.

**Comment by Stratis-Dermanoutsos** [comment]
Same issue on expo app. react-native version: `0.69.5`

**Comment by Thomasosho** [comment]
use this expo package instead [Expo Checkbox](https://docs.expo.dev/versions/latest/sdk/checkbox/)

**Comment by kmkz-69** [comment]
I use react-native start --reset-cache and ./gradlew clean
and it works for me.
