### ISSUE TITLE
CheckBox component gives typescript error: JSX element class does not support attributes because it does not have a 'props' property

### ISSUE THREAD

**Issue by t-ricci-digit** [react-native-checkbox/react-native-checkbox#196]
![image](https://user-images.githubusercontent.com/118282270/235161454-161c0e0d-d4ed-47ca-b7c4-861f1c6edaec.png)

Using Typescript 5.0.4, react-native 0.71.2 and react-native-checkbox 0.5.15

**Comment by 0x10Ayoub** [comment]
the same issue, I think it's related to react native 0.71.x You can use the latest Stable version which is 0.70.9  until it's fixed
## context 
checkbox relies on NativeMethodsMixin instead NativeMethods  which is got deprecated in the latest version of React Native

**Comment by techgerm** [comment]
Is there a workaround to this so aren't forced to downgrade to React Native <0.71.x?

**Comment by techgerm** [comment]
This was actually fixed in `0.5.15`: https://github.com/react-native-checkbox/react-native-checkbox/pull/190#issuecomment-1465352020
