### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager, IOS

### ISSUE THREAD

**Issue by dembijeremias** [react-native-checkbox/react-native-checkbox#205]
IOS not working
@react-native-community/checkbox version 0.5.15

I'm using React Native version 0.63.4.

![Simulator Screen Shot - Iphone 11 Pro Max - 2023-08-07 at 16 35 43](https://github.com/react-native-checkbox/react-native-checkbox/assets/125599429/c1080cdd-c6fd-4bee-ba5b-e20c0ae6d61e)

**Comment by ryansherby** [comment]
Can you share your solution to this issue for pure React Native managed workflow?
