### ISSUE TITLE
[react-native-windows] Missing Publisher Details in the details tab under dll Properties

### ISSUE THREAD

**Issue by NikhiRaya** [react-native-checkbox/react-native-checkbox#206]
The CheckboxWindows.dll is missing versioning/publisher details set in their metadata.

Currently, the publisher information is not available in the properties (screenshot below), and this absence of publisher details is causing issues with AppLocker (a security tool). AppLocker can sometimes block updates to DLLs if they do not have proper versioning/publisher details set in their metadata.

<img width="504" alt="image" src="https://github.com/react-native-checkbox/react-native-checkbox/assets/110552664/e21e2f9b-5b13-4d54-9596-bc7beaa0fde9">

**Comment by nicholaslee119** [comment]
Thanks for your PR
