### ISSUE TITLE
Issue with react-native-checkbox 0.5.4

### ISSUE THREAD

**Issue by mlecoq** [react-native-checkbox/react-native-checkbox#89]
Hi,

After updating from **0.5.3 to 0.5.4**, I have the following message when I run `pod install`

`Errno::ENOENT - No such file or directory @ realpath_rec - /Users/mlecoq/work/archireport/dev/archireport_mobile/node_modules/@react-native-community/checkbox/ios/Pods/Headers/Private/BEMCheckBox/iOS`

Going back to 0.5.3 solves the issue

**Comment by aliasger-rashid** [comment]
@mlecoq How did you change the pods to 0.5.3 ? When I tried putting the specific pod in pod file it gives me error.

**Comment by thnha** [comment]
> @mlecoq How did you change the pods to 0.5.3 ? When I tried putting the specific pod in pod file it gives me error.

"@react-native-community/checkbox": "0.5.3",

**Comment by aliasger-rashid** [comment]
@thnha 
> "@react-native-community/checkbox": "0.5.3", (don't -> "^0.5.3")

This worked , I am curious what is the difference when we use "^" .
Cause I spent hours yesterday to fix it and remove ^ fixed it ultimately from your help.
Thanks

**Comment by mlecoq** [comment]
@aliasger-rashid ^ means `include everything greater than a particular version in the same major range`

**Comment by parnekov** [comment]
Can not install PODS in 0.54.      0.53 - OK

**Comment by nicholaslee119** [comment]
Sorry for the trouble, We just fix this bug in the current version 0.5.5
